#!/bin/sh
rm *.o 
rm *.obj 
rm -rf manual 
rm -rf predefined 
rm -rf icons 
rm unistd.h
tqfind -lname \* -maxdepth 1 | xargs rm
rm tqmoc_*
rm images.h
rm gen_*
rm -rf kregexpeditor*
rm Makefile
rm kregexpeditor.zip
